p_value_threshold: 0.05 # the p value threshold used for the statistical test
sequence_encoding: continuous_kmer  # split sequence into overlapping k-mers
k: 3  # k-mer length if k-mers are not gapped
k_left: 1  # left k-mer length for gapped k-mers
k_right: 1  # right k-mer length for gapped k-mer
max_gap: 0  # maximum gap for gapped k-mers
min_gap: 0  # minimum gap for gapped k-mers