
name: build_docs

on:

  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: make html & commit the changes
        run: |
          sphinx-build -b html ./docs_source ./docs
          git config --global user.email "github@action.com"
          git config user.name "pavlovicmilena"
          git add -f ./docs
          git commit -m 'update docs'

      - name: push changes to gh-pages to show automatically
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true