name: Python application

on:
  push:
    branches: [ main ]
    paths: [ '**.py', '**.yaml' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.py', '**.yaml' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy
        pip install -r requirements.txt
        stitchrdl -s human # download human data for stitchr for exporting full sequences
    - name: Test with pytest
      env:
        PYTHONFAULTHANDLER: 1 
      run: python -m pytest
